---

  - name: Assures /etc/apache2/ssl dir exists
    sudo: yes
    file: path=/etc/apache2/ssl state=directory

  - name: Create self-signed SSL cert
    sudo: yes
    command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=US" -keyout /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt

  # @TODO should be used apache template and apache role. Currently used only for CI server.
  - name: Copy SSL apache vhost file
    synchronize: src=files/sites-enabled/default-ssl.conf dest=/etc/apache2/sites-enabled/default-ssl.conf
    sudo: yes
    tags:
      - apache
      - php-stack
      - ssl
    notify: Restart apache
    when: cibox_ssl_enable_host == true
